version: "3"
services: 
    node-translate:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/src
            - /src/node_modules
        environment: 
            - NODE_ENV=development
        env_file: 
            - ./config/dev.env
        command: npm run dev